# Generated by Django 5.0.1 on 2024-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashText', models.CharField(max_length=200)),
                ('hashType', models.CharField(max_length=200)),
            ],
        ),
    ]
