# Generated by Django 5.0.1 on 2024-01-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehasher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashCatMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
    ]
